import numpy as np 
a = np.array([5,6,9])
print("a[0]:",a[0])
c= np.array([[1,2],[3,4],[5,6]])
print("c", c)
print(c.ndim)
print("c.itemsize", c.itemsize)
d= np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
print("d.itemsize", d.itemsize)
print("c", c)
print(c.size)
print("d is",  d)
print("size of d is", d.size)
e = np.array([[1,2], [2,3],[4,5]], dtype= complex)
print("e", e)
i = np.zeros((3,4))
print("i is ", i)
j = np.ones((4,3))
print("j is", j)

f = np.arange(1,3)
print("f is", f)

k = np.arange(1,10,2)
print("k is", k)
g= np.linspace(1,10,10) 
print("g:" ,g)
print("d.shape", d.shape)
print(d.reshape(2,3))
print(d.ravel())
print(d.min())
print(d.max())
print(d.sum(axis = 0))
print(d.sum(axis=1))
print("d is", d)
print(np.sqrt(d))
print("e + d is",e+ d)
print("e-d is", e-d)
print("e/d is", e/d)
print("E", e)
k= e.dot(d)
print(k)
